apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t8gvb15ws-python 
  janus-idp.io/tekton: t8gvb15ws-python
  backstage.io/kubernetes-id: t8gvb15ws-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t8gvb15ws-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  